// Generated by gencpp from file task4_pkg/count_sum.msg
// DO NOT EDIT!


#ifndef TASK4_PKG_MESSAGE_COUNT_SUM_H
#define TASK4_PKG_MESSAGE_COUNT_SUM_H

#include <ros/service_traits.h>


#include <task4_pkg/count_sumRequest.h>
#include <task4_pkg/count_sumResponse.h>


namespace task4_pkg
{

struct count_sum
{

typedef count_sumRequest Request;
typedef count_sumResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct count_sum
} // namespace task4_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::task4_pkg::count_sum > {
  static const char* value()
  {
    return "875493d2ec8f0bdc18c62960322c94b7";
  }

  static const char* value(const ::task4_pkg::count_sum&) { return value(); }
};

template<>
struct DataType< ::task4_pkg::count_sum > {
  static const char* value()
  {
    return "task4_pkg/count_sum";
  }

  static const char* value(const ::task4_pkg::count_sum&) { return value(); }
};


// service_traits::MD5Sum< ::task4_pkg::count_sumRequest> should match
// service_traits::MD5Sum< ::task4_pkg::count_sum >
template<>
struct MD5Sum< ::task4_pkg::count_sumRequest>
{
  static const char* value()
  {
    return MD5Sum< ::task4_pkg::count_sum >::value();
  }
  static const char* value(const ::task4_pkg::count_sumRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::task4_pkg::count_sumRequest> should match
// service_traits::DataType< ::task4_pkg::count_sum >
template<>
struct DataType< ::task4_pkg::count_sumRequest>
{
  static const char* value()
  {
    return DataType< ::task4_pkg::count_sum >::value();
  }
  static const char* value(const ::task4_pkg::count_sumRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::task4_pkg::count_sumResponse> should match
// service_traits::MD5Sum< ::task4_pkg::count_sum >
template<>
struct MD5Sum< ::task4_pkg::count_sumResponse>
{
  static const char* value()
  {
    return MD5Sum< ::task4_pkg::count_sum >::value();
  }
  static const char* value(const ::task4_pkg::count_sumResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::task4_pkg::count_sumResponse> should match
// service_traits::DataType< ::task4_pkg::count_sum >
template<>
struct DataType< ::task4_pkg::count_sumResponse>
{
  static const char* value()
  {
    return DataType< ::task4_pkg::count_sum >::value();
  }
  static const char* value(const ::task4_pkg::count_sumResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TASK4_PKG_MESSAGE_COUNT_SUM_H
