// Generated by gencpp from file task3_pkg/words_counterRequest.msg
// DO NOT EDIT!


#ifndef TASK3_PKG_MESSAGE_WORDS_COUNTERREQUEST_H
#define TASK3_PKG_MESSAGE_WORDS_COUNTERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace task3_pkg
{
template <class ContainerAllocator>
struct words_counterRequest_
{
  typedef words_counterRequest_<ContainerAllocator> Type;

  words_counterRequest_()
    : sentence()  {
    }
  words_counterRequest_(const ContainerAllocator& _alloc)
    : sentence(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _sentence_type;
  _sentence_type sentence;





  typedef boost::shared_ptr< ::task3_pkg::words_counterRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::task3_pkg::words_counterRequest_<ContainerAllocator> const> ConstPtr;

}; // struct words_counterRequest_

typedef ::task3_pkg::words_counterRequest_<std::allocator<void> > words_counterRequest;

typedef boost::shared_ptr< ::task3_pkg::words_counterRequest > words_counterRequestPtr;
typedef boost::shared_ptr< ::task3_pkg::words_counterRequest const> words_counterRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::task3_pkg::words_counterRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::task3_pkg::words_counterRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::task3_pkg::words_counterRequest_<ContainerAllocator1> & lhs, const ::task3_pkg::words_counterRequest_<ContainerAllocator2> & rhs)
{
  return lhs.sentence == rhs.sentence;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::task3_pkg::words_counterRequest_<ContainerAllocator1> & lhs, const ::task3_pkg::words_counterRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace task3_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::task3_pkg::words_counterRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::task3_pkg::words_counterRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::task3_pkg::words_counterRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::task3_pkg::words_counterRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task3_pkg::words_counterRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task3_pkg::words_counterRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::task3_pkg::words_counterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3ee8e7a1b3ec1e5b34263db750df6246";
  }

  static const char* value(const ::task3_pkg::words_counterRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3ee8e7a1b3ec1e5bULL;
  static const uint64_t static_value2 = 0x34263db750df6246ULL;
};

template<class ContainerAllocator>
struct DataType< ::task3_pkg::words_counterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "task3_pkg/words_counterRequest";
  }

  static const char* value(const ::task3_pkg::words_counterRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::task3_pkg::words_counterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string sentence\n"
;
  }

  static const char* value(const ::task3_pkg::words_counterRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::task3_pkg::words_counterRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sentence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct words_counterRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::task3_pkg::words_counterRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::task3_pkg::words_counterRequest_<ContainerAllocator>& v)
  {
    s << indent << "sentence: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.sentence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TASK3_PKG_MESSAGE_WORDS_COUNTERREQUEST_H
