// Generated by gencpp from file task3_pkg/words_counter.msg
// DO NOT EDIT!


#ifndef TASK3_PKG_MESSAGE_WORDS_COUNTER_H
#define TASK3_PKG_MESSAGE_WORDS_COUNTER_H

#include <ros/service_traits.h>


#include <task3_pkg/words_counterRequest.h>
#include <task3_pkg/words_counterResponse.h>


namespace task3_pkg
{

struct words_counter
{

typedef words_counterRequest Request;
typedef words_counterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct words_counter
} // namespace task3_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::task3_pkg::words_counter > {
  static const char* value()
  {
    return "7493e9879e62bc96956efab2440a9c04";
  }

  static const char* value(const ::task3_pkg::words_counter&) { return value(); }
};

template<>
struct DataType< ::task3_pkg::words_counter > {
  static const char* value()
  {
    return "task3_pkg/words_counter";
  }

  static const char* value(const ::task3_pkg::words_counter&) { return value(); }
};


// service_traits::MD5Sum< ::task3_pkg::words_counterRequest> should match
// service_traits::MD5Sum< ::task3_pkg::words_counter >
template<>
struct MD5Sum< ::task3_pkg::words_counterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::task3_pkg::words_counter >::value();
  }
  static const char* value(const ::task3_pkg::words_counterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::task3_pkg::words_counterRequest> should match
// service_traits::DataType< ::task3_pkg::words_counter >
template<>
struct DataType< ::task3_pkg::words_counterRequest>
{
  static const char* value()
  {
    return DataType< ::task3_pkg::words_counter >::value();
  }
  static const char* value(const ::task3_pkg::words_counterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::task3_pkg::words_counterResponse> should match
// service_traits::MD5Sum< ::task3_pkg::words_counter >
template<>
struct MD5Sum< ::task3_pkg::words_counterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::task3_pkg::words_counter >::value();
  }
  static const char* value(const ::task3_pkg::words_counterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::task3_pkg::words_counterResponse> should match
// service_traits::DataType< ::task3_pkg::words_counter >
template<>
struct DataType< ::task3_pkg::words_counterResponse>
{
  static const char* value()
  {
    return DataType< ::task3_pkg::words_counter >::value();
  }
  static const char* value(const ::task3_pkg::words_counterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TASK3_PKG_MESSAGE_WORDS_COUNTER_H
